# Problem 1

(a)

![](nn_drawing.png)

(b)

In [28]:
import numpy as np

@np.vectorize
def h(x):
    if x <= 0:
        return 0
    else:
        return x
    
@np.vectorize
def h_prime(x):
    if x <= 0:
        return 0
    else:
        return 1

W1 = np.array([
    [0.2, 0.44],
    [0.32, -0.1],
    [0.1, 0.17],
])

b1 = np.array([0.47, 0.2, -0.32])

W2 = np.array([
    [0.87, 0.04, 0.52],
])

b2 = np.array([0.3])

x1 = np.array([-0.14, 0.15])
q1 = h(x1.T@W1.T + b1.T)
print(q1)
print(q1.T@W2.T + b2.T)

[0.508  0.1402 0.    ]
[0.747568]


(c)

In classification, the output of the neural should be of dimension M (the number of classes), which feeds into an additional softmax activation function in order to predict the probabilities of each class. Since the neural net defined above is a single number on the output, instead of M outputs, we know that it cannot possibly be used for classification.

# Problem 2

We will follow the steps on page 143 of the textbook

In [29]:
x = np.array([1, -1])
y = np.array([0.1])

q0 = x
print(f"q0 = x = {x}")
z1 = W1@q0 + b1
print(f"z1 = {z1}")
q1 = h(z1)
print(f"q1 = {q1}")
z2 = W2@q1+b2
print(f"z2 = {z2}")
J = (y - z2)**2
print(f"J(theta) = {J}")

q0 = x = [ 1 -1]
z1 = [ 0.23  0.62 -0.39]
q1 = [0.23 0.62 0.  ]
z2 = [0.5249]
J(theta) = [0.18054001]


In [30]:
q0.shape

(2,)

In [31]:
dz2 = -2*(y - z2)

dW2 = dz2 @ q1.reshape((len(q1), 1)).T
db2 = dz2

dq1 = W2.T@dz2
dz1 = dq1 * h_prime(z2)
dW1 = dz1.reshape((len(dz1), 1)) @ q0.reshape((len(q0), 1)).T
db1 = dz1

In [32]:
gamma = 0.05
W1_new = W1 - gamma*dW1
b1_new = b1 - gamma*db1

W2_new = W2 - gamma*dW2
b2_new = b2 - gamma*db2

In [33]:
x = np.array([1, -1])
y = np.array([0.1])

q0 = x
print(f"q0 = x = {x}")
z1 = W1_new@q0 + b1_new
print(f"z1 = {z1}")
q1 = h(z1)
print(f"q1 = {q1}")
z2 = W2_new@q1+b2_new
print(f"z2 = {z2}")
J = (y - z2)**2
print(f"J(theta) = {J}")

q0 = x = [ 1 -1]
z1 = [ 0.1191011  0.6149012 -0.4562844]
q1 = [0.1191011 0.6149012 0.       ]
z2 = [0.36836123]
J(theta) = [0.07201775]


In [34]:
# Q = np.array([
#     q1,
# ])

# Z = np.array([
#     z1.reshape(),
#     np.atleast_1d(z2),
# ])

# Problem 3

In [43]:
def compute_pooling_layer_output(input, stride=2, method=np.max):
    output = np.zeros((input.shape[0]//stride, input.shape[1]//stride))
    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            output[i, j] = method(input[stride*i:stride*(i+1), stride*j:stride*(j+1)])
    return output

pooling_layer_input = np.array([
    [5, 2, 1, 0, 2, 4],
    [2, 3, 0, 3, 4, 2],
    [5, 7, 7, 4, 3, 4],
    [0, 4, 9, 0, 2, 3],
    [1, 3, 5, 2, 6, 2],
    [2, 2, 4, 3, 8, 0]
])

print(f"Using Max Pooling: \n{compute_pooling_layer_output(pooling_layer_input, stride=2, method=np.max)}")
print(f"Using Average Pooling: \n{compute_pooling_layer_output(pooling_layer_input, stride=2, method=np.mean)}")

Using Max Pooling: 
[[5. 3. 4.]
 [7. 9. 4.]
 [3. 5. 8.]]
Using Average Pooling: 
[[3.  1.  3. ]
 [4.  5.  3. ]
 [2.  3.5 4. ]]


# Problem 4

![](ex6p3_table.png)